apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-tool-bench-settings
spec:
  forms:
    - group: basic
      label: 通用设置
      formSchema:
        - $formkit: radio
          name: antvG2
          id: antvG2
          label: AntV G2
          value: false
          options:
            - value: true
              label: 启用
            - value: false
              label: 禁用
        - $formkit: radio
          name: antvX6
          id: antvX6
          label: AntV X6
          value: false
          options:
            - value: true
              label: 启用
            - value: false
              label: 禁用
        - $formkit: text
          label: 目录页标题
          name: directory
          validation: required
          value: "目录"
        - $formkit: text
          label: GitHub Token
          name: githubToken
          validation: required
          value: "GitHub Token"
          help: "填入你的GitHub Token（需要能获取你Public仓库信息的能力），用于请求GitHub API GraphQL"
        - $formkit: text
          label: 和风天气私钥
          name: qWeatherPrivateKey
          help: "填入你的和风天气应用私钥，用于请求和风天气API"
          validation: required
    - group: post
      label: 文章设置
      formSchema:
        - $formkit: radio
          name: enableToolElement
          id: enableToolElement
          label: tool标签
          value: true
          help: "对文章页是否启用<tool-?>标签的支持"
          options:
            - value: true
              label: 启用
            - value: false
              label: 禁用
        - $formkit: radio
          name: enableCountMeta
          id: enableCountMeta
          label: 额外tool标签
          value: true
          help: "对文章页是否启用字数统计和图片统计的额外信息"
          options:
            - value: true
              label: 启用
            - value: false
              label: 禁用
        - $formkit: textarea
          name: head
          id: head
          label: 文首追加
          help: "在所有文章的首部插入额外的HTML代码"
        - $formkit: textarea
          name: tail
          id: tail
          label: 文末追加
          help: "在所有文章的尾部插入额外的HTML代码"
